<a href="https://colab.research.google.com/github/armeh429/A-journey-for-learning-advanced-tensorflow/blob/main/Basic_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
import numpy as np

In [3]:
var_string = tf.Variable("Elephant" , dtype= tf.string)

In [5]:
its_complicated = tf.Variable(4 + 3j, dtype=tf.complex64)

In [7]:
first_primes = tf.Variable([2,3,5,7,11] , dtype=tf.int32)

In [8]:
linear_square = tf.Variable([[4,9], [16,25] ] , dtype=tf.int32)

constant tensor 

In [10]:
tensor = tf.constant([1,2,3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [12]:
tensor = tf.constant(-1.0 , shape=[2,3])
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

In [15]:
tensor = tf.constant([1,2,3,4,5,6] , shape=(2,3))
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [18]:
# Try this and look at the error
# Try to change the input to `shape` to avoid an error
tmp = tf.constant([1,2,3,4,5,6])
tf.reshape(tmp, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [20]:
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
# Cast tensor x into float32. Notice the change in the dtype.
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(25,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)>

In [24]:
try:
    # This will produce a ValueError
    temp = tf.Variable([1,2,3,4], shape=None )
except ValueError as v:
    # See what the ValueError says
    print(v)

In [25]:
temp

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>